title: <p align="center"> Syarifah Rosita Dewi </p>

logo: <img align="center"> "/images/image.png?raw=true" </img># your photo (or logo) here
# logo: <img class="avatar is-rounded" src="/images/image.png?raw=true" alt="Lei Mao">

description:
  <p align="center">
  <a href="pdf/Resume_Syarifah Rosita Dewi.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/syarifahrositadewi/">LinkedIn</a> |
  <a href="https://github.com/srositad">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing BS degree in Statistics at Islamic University of Indonesia.
  <br><br>
  I am currently a Data Scientist with 4+ years of total experience in building data-intensive applications, overcoming complex 
  architectural, and scalability issues in diverse industries.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-XT1T4NMQTM # your Google Analytics tracking ID here
