title: Syarifah Rosita Dewi # your name (or website title) here
# logo: "/images/profil.jpg?raw=true" # your photo (or logo) here
logo : <img class="avatar is-rounded" src="/images/1671595982.jpg?raw=true" alt="Lei Mao">
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/syarifahrositadewi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-XT1T4NMQTM # your Google Analytics tracking ID here
