title: <p align="center"> Syarifah Rosita Dewi </p>

logo: "/images/image.png?raw=true" # your photo (or logo) here
# logo: <img class="avatar is-rounded" src="/images/image.png?raw=true" alt="Lei Mao">

description:
  <p align="center">
  <a href="pdf/Resume_Syarifah Rosita Dewi.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/syarifahrositadewi/">LinkedIn</a> |
  <a href="https://github.com/srositad">GitHub</a>
  </p>
  
  <p align="justify">
  I love bringing efficiency to things. I have a passion for solving problems, building sustainable solutions, and learning as much as I can about things that interest me. 
  I'm also excited about talking to people who are interested in productivity and self-improvement.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-XT1T4NMQTM # your Google Analytics tracking ID here
